# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  blazorhostedserver:
    image: blazorhostedserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 4080:80
      - 4443:443
  blazorhostedclient:
    image: blazorhostedclient
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - 5080:80
      - 5443:443
  
